export const DISHES_LOADING = 'DISHES_LOADING';
export const ADD_DISHES = 'ADD_DISHES';
export const ADD_DISHES_FAILED = 'ADD_DISHES_FAILED';

export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const ADD_COMMENTS_FAILED = 'COMMENTS_FAILED';
export const POST_COMMENT_FAILED = 'POST_COMMENT_FAILED';

export const STAFFS_LOADING = 'STAFFS_LOADING';
export const ADD_STAFFS = 'ADD_STAFFS';
export const ADD_STAFFS_FAILED = 'STAFFS_FAILED';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';